-- Rebuild Smart Locator access tokens from access-token.xlsx
-- Columns: Unit, Office, Role, access_token

drop table if exists public.smart_locator_access_tokens cascade;

create table public.smart_locator_access_tokens (
  id uuid primary key default gen_random_uuid(),
  unit text not null default '',
  office text not null default '',
  role text not null default 'Encoder'
    check (role in ('Encoder', 'System Administrator')),
  access_token text not null,
  is_active boolean not null default true,
  session text,
  session_started_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index smart_locator_access_tokens_access_token_unique_idx
  on public.smart_locator_access_tokens (lower(trim(access_token)));

create unique index smart_locator_access_tokens_session_unique_idx
  on public.smart_locator_access_tokens (session)
  where session is not null;

create index smart_locator_access_tokens_office_unit_idx
  on public.smart_locator_access_tokens (office, unit);

alter table public.smart_locator_access_tokens enable row level security;

insert into public.smart_locator_access_tokens (access_token, office, unit, role, is_active)
values
('SL-CAVITE-PPO-ALFONSO-MPS-869E','Cavite PPO','Alfonso MPS','Encoder',true),
('SL-CAVITE-PPO-AMADEO-MPS-EB54','Cavite PPO','Amadeo MPS','Encoder',true),
('SL-CAVITE-PPO-BACOOR-CCPS-D3FD','Cavite PPO','Bacoor CCPS','Encoder',true),
('SL-CAVITE-PPO-CARMONA-MPS-369D','Cavite PPO','Carmona MPS','Encoder',true),
('SL-CAVITE-PPO-CAVITE-CCPS-AF87','Cavite PPO','Cavite CCPS','Encoder',true),
('SL-CAVITE-PPO-DASMARI-AS-CCPS-D878','Cavite PPO','Dasmariñas CCPS','Encoder',true),
('SL-CAVITE-PPO-GEN-EMILLIO-AGUINA-F109','Cavite PPO','Gen. Emillio Aguinaldo MPS','Encoder',true),
('SL-CAVITE-PPO-GEN-TRIAS-CCPS-ABA7','Cavite PPO','Gen. Trias CCPS','Encoder',true),
('SL-CAVITE-PPO-GEN-MARIANO-ALVARE-ED58','Cavite PPO','Gen. Mariano Alvarez MPS','Encoder',true),
('SL-CAVITE-PPO-IMUS-CCPS-E65D','Cavite PPO','Imus CCPS','Encoder',true),
('SL-CAVITE-PPO-INDANG-MPS-588E','Cavite PPO','Indang MPS','Encoder',true),
('SL-CAVITE-PPO-KAWIT-MPS-8C3E','Cavite PPO','Kawit MPS','Encoder',true),
('SL-CAVITE-PPO-MAGALLANES-MPS-C685','Cavite PPO','Magallanes MPS','Encoder',true),
('SL-CAVITE-PPO-MARAGONDON-MPS-BB6B','Cavite PPO','Maragondon MPS','Encoder',true),
('SL-CAVITE-PPO-MENDEZ-MPS-CA0E','Cavite PPO','Mendez MPS','Encoder',true),
('SL-CAVITE-PPO-NAIC-MPS-6B31','Cavite PPO','Naic MPS','Encoder',true),
('SL-CAVITE-PPO-NOVELETA-MPS-9585','Cavite PPO','Noveleta MPS','Encoder',true),
('SL-CAVITE-PPO-ROSARIO-MPS-29A8','Cavite PPO','Rosario MPS','Encoder',true),
('SL-CAVITE-PPO-SILANG-MPS-F686','Cavite PPO','Silang MPS','Encoder',true),
('SL-CAVITE-PPO-TAGAYTAY-CCPS-3535','Cavite PPO','Tagaytay CCPS','Encoder',true),
('SL-CAVITE-PPO-TANZA-MPS-ADBA','Cavite PPO','Tanza MPS','Encoder',true),
('SL-CAVITE-PPO-TERNATE-MPS-EEAF','Cavite PPO','Ternate MPS','Encoder',true),
('SL-CAVITE-PPO-TRECE-MARTIRES-CCP-1A19','Cavite PPO','Trece Martires CCPS','Encoder',true),
('SL-LAGUNA-PPO-ALAMINOS-MPS-783D','Laguna PPO','Alaminos MPS','Encoder',true),
('SL-LAGUNA-PPO-BAY-MPS-ADB3','Laguna PPO','Bay MPS','Encoder',true),
('SL-LAGUNA-PPO-BI-AN-CCPS-C7EF','Laguna PPO','Biñan CCPS','Encoder',true),
('SL-LAGUNA-PPO-CABUYAO-CCPS-2F7D','Laguna PPO','Cabuyao CCPS','Encoder',true),
('SL-LAGUNA-PPO-CALAMBA-CCPS-EC91','Laguna PPO','Calamba CCPS','Encoder',true),
('SL-LAGUNA-PPO-CALAUAN-MPS-8895','Laguna PPO','Calauan MPS','Encoder',true),
('SL-LAGUNA-PPO-CAVINTI-MPS-463F','Laguna PPO','Cavinti MPS','Encoder',true),
('SL-LAGUNA-PPO-FAMY-MPS-E80D','Laguna PPO','Famy MPS','Encoder',true),
('SL-LAGUNA-PPO-KALAYAAN-MPS-E30B','Laguna PPO','Kalayaan MPS','Encoder',true),
('SL-LAGUNA-PPO-LILIW-MPS-C118','Laguna PPO','Liliw MPS','Encoder',true),
('SL-LAGUNA-PPO-LOS-BA-OS-MPS-F862','Laguna PPO','Los Baños MPS','Encoder',true),
('SL-LAGUNA-PPO-LUISIANA-MPS-0D13','Laguna PPO','Luisiana MPS','Encoder',true),
('SL-LAGUNA-PPO-LUMBAN-MPS-6FD0','Laguna PPO','Lumban MPS','Encoder',true),
('SL-LAGUNA-PPO-MABITAC-MPS-E4EC','Laguna PPO','Mabitac MPS','Encoder',true),
('SL-LAGUNA-PPO-MAGDALENA-MPS-9D56','Laguna PPO','Magdalena MPS','Encoder',true),
('SL-LAGUNA-PPO-MAJAYJAY-MPS-2587','Laguna PPO','Majayjay MPS','Encoder',true),
('SL-LAGUNA-PPO-NAGCARLAN-MPS-E39F','Laguna PPO','Nagcarlan MPS','Encoder',true),
('SL-LAGUNA-PPO-PAETE-MPS-0F8A','Laguna PPO','Paete MPS','Encoder',true),
('SL-LAGUNA-PPO-PAGSANJAN-MPS-85DA','Laguna PPO','Pagsanjan MPS','Encoder',true),
('SL-LAGUNA-PPO-PAKIL-MPS-ACBA','Laguna PPO','Pakil MPS','Encoder',true),
('SL-LAGUNA-PPO-PANGIL-MPS-DD89','Laguna PPO','Pangil MPS','Encoder',true),
('SL-LAGUNA-PPO-PILA-MPS-32EB','Laguna PPO','Pila MPS','Encoder',true),
('SL-LAGUNA-PPO-RIZAL-MPS-2721','Laguna PPO','Rizal MPS','Encoder',true),
('SL-LAGUNA-PPO-SAN-PABLO-CCPS-BEF3','Laguna PPO','San Pablo CCPS','Encoder',true),
('SL-LAGUNA-PPO-SAN-PEDRO-CCPS-671B','Laguna PPO','San Pedro CCPS','Encoder',true),
('SL-LAGUNA-PPO-SANTA-CRUZ-MPS-A89E','Laguna PPO','Santa Cruz MPS','Encoder',true),
('SL-LAGUNA-PPO-SANTA-MARIA-MPS-F018','Laguna PPO','Santa Maria MPS','Encoder',true),
('SL-LAGUNA-PPO-SANTA-ROSA-CCPS-25C0','Laguna PPO','Santa Rosa CCPS','Encoder',true),
('SL-LAGUNA-PPO-SINILOAN-MPS-7A4C','Laguna PPO','Siniloan MPS','Encoder',true),
('SL-LAGUNA-PPO-VICTORIA-MPS-07D2','Laguna PPO','Victoria MPS','Encoder',true),
('SL-BATANGAS-PPO-AGONCILLO-MPS-8F70','Batangas PPO','Agoncillo MPS','Encoder',true),
('SL-BATANGAS-PPO-ALITAGTAG-MPS-4530','Batangas PPO','Alitagtag MPS','Encoder',true),
('SL-BATANGAS-PPO-BALAYAN-MPS-C598','Batangas PPO','Balayan MPS','Encoder',true),
('SL-BATANGAS-PPO-BALETE-MPS-B4DB','Batangas PPO','Balete MPS','Encoder',true),
('SL-BATANGAS-PPO-BATANGAS-CCPS-8C84','Batangas PPO','Batangas CCPS','Encoder',true),
('SL-BATANGAS-PPO-BAUAN-MPS-8ECF','Batangas PPO','Bauan MPS','Encoder',true),
('SL-BATANGAS-PPO-CALACA-MPS-C0D6','Batangas PPO','Calaca MPS','Encoder',true),
('SL-BATANGAS-PPO-CALATAGAN-MPS-18E5','Batangas PPO','Calatagan MPS','Encoder',true),
('SL-BATANGAS-PPO-CUENCA-MPS-E21C','Batangas PPO','Cuenca MPS','Encoder',true),
('SL-BATANGAS-PPO-IBAAN-MPS-2143','Batangas PPO','Ibaan MPS','Encoder',true),
('SL-BATANGAS-PPO-LAUREL-MPS-78F5','Batangas PPO','Laurel MPS','Encoder',true),
('SL-BATANGAS-PPO-LEMERY-MPS-C9FA','Batangas PPO','Lemery MPS','Encoder',true),
('SL-BATANGAS-PPO-LIAN-MPS-BBD6','Batangas PPO','Lian MPS','Encoder',true),
('SL-BATANGAS-PPO-LIPA-CCPS-9314','Batangas PPO','Lipa CCPS','Encoder',true),
('SL-BATANGAS-PPO-LOBO-MPS-5394','Batangas PPO','Lobo MPS','Encoder',true),
('SL-BATANGAS-PPO-MABINI-MPS-4E11','Batangas PPO','Mabini MPS','Encoder',true),
('SL-BATANGAS-PPO-MALVAR-MPS-A6C0','Batangas PPO','Malvar MPS','Encoder',true),
('SL-BATANGAS-PPO-MATAAS-NA-KAHOY-MP-7AF0','Batangas PPO','Mataas na Kahoy MPS','Encoder',true),
('SL-BATANGAS-PPO-NASUGBU-MPS-6804','Batangas PPO','Nasugbu MPS','Encoder',true),
('SL-BATANGAS-PPO-PADRE-GARCIA-MPS-F569','Batangas PPO','Padre Garcia MPS','Encoder',true),
('SL-BATANGAS-PPO-ROSARIO-MPS-F9D2','Batangas PPO','Rosario MPS','Encoder',true),
('SL-BATANGAS-PPO-SAN-JOSE-MPS-9E32','Batangas PPO','San Jose MPS','Encoder',true),
('SL-BATANGAS-PPO-SAN-JUAN-MPS-B409','Batangas PPO','San Juan MPS','Encoder',true),
('SL-BATANGAS-PPO-SAN-LUIS-MPS-A78F','Batangas PPO','San Luis MPS','Encoder',true),
('SL-BATANGAS-PPO-SAN-NICOLAS-MPS-F668','Batangas PPO','San Nicolas MPS','Encoder',true),
('SL-BATANGAS-PPO-SAN-PASCUAL-MPS-2C17','Batangas PPO','San Pascual MPS','Encoder',true),
('SL-BATANGAS-PPO-SANTA-TERESITA-MPS-65AB','Batangas PPO','Santa Teresita MPS','Encoder',true),
('SL-BATANGAS-PPO-SANTO-TOMAS-CCPS-1287','Batangas PPO','Santo Tomas CCPS','Encoder',true),
('SL-BATANGAS-PPO-TAAL-MPS-6DAE','Batangas PPO','Taal MPS','Encoder',true),
('SL-BATANGAS-PPO-TALISAY-MPS-7755','Batangas PPO','Talisay MPS','Encoder',true),
('SL-BATANGAS-PPO-TANAUAN-CCPS-6721','Batangas PPO','Tanauan CCPS','Encoder',true),
('SL-BATANGAS-PPO-TAYSAN-MPS-E5FD','Batangas PPO','Taysan MPS','Encoder',true),
('SL-BATANGAS-PPO-TINGLOY-MPS-186A','Batangas PPO','Tingloy MPS','Encoder',true),
('SL-BATANGAS-PPO-TUY-MPS-4A6B','Batangas PPO','Tuy MPS','Encoder',true),
('SL-RIZAL-PPO-ANGONO-MPS-36DA','Rizal PPO','Angono MPS','Encoder',true),
('SL-RIZAL-PPO-ANTIPOLO-CCPS-E653','Rizal PPO','Antipolo CCPS','Encoder',true),
('SL-RIZAL-PPO-BARAS-MPS-7DB5','Rizal PPO','Baras MPS','Encoder',true),
('SL-RIZAL-PPO-BINANGONAN-MPS-6186','Rizal PPO','Binangonan MPS','Encoder',true),
('SL-RIZAL-PPO-CAINTA-MPS-3D1E','Rizal PPO','Cainta MPS','Encoder',true),
('SL-RIZAL-PPO-CARDONA-MPS-1E15','Rizal PPO','Cardona MPS','Encoder',true),
('SL-RIZAL-PPO-JALA-JALA-MPS-CDD6','Rizal PPO','Jala-Jala MPS','Encoder',true),
('SL-RIZAL-PPO-MORONG-MPS-6ADB','Rizal PPO','Morong MPS','Encoder',true),
('SL-RIZAL-PPO-PILILLIA-MPS-79FF','Rizal PPO','Pilillia MPS','Encoder',true),
('SL-RIZAL-PPO-RODRIQUEZ-MPS-0997','Rizal PPO','Rodriquez MPS','Encoder',true),
('SL-RIZAL-PPO-SAN-MATEO-MPS-50CC','Rizal PPO','San Mateo MPS','Encoder',true),
('SL-RIZAL-PPO-TANAY-MPS-F2F4','Rizal PPO','Tanay MPS','Encoder',true),
('SL-RIZAL-PPO-TAYTAY-MPS-7878','Rizal PPO','Taytay MPS','Encoder',true),
('SL-RIZAL-PPO-TERESA-MPS-9826','Rizal PPO','Teresa MPS','Encoder',true),
('SL-QUEZON-PPO-AGDANGAN-MPS-649E','Quezon PPO','Agdangan MPS','Encoder',true),
('SL-QUEZON-PPO-ALABAT-MPS-CDFF','Quezon PPO','Alabat MPS','Encoder',true),
('SL-QUEZON-PPO-ATIMONAN-MPS-3BF8','Quezon PPO','Atimonan MPS','Encoder',true),
('SL-QUEZON-PPO-BUENAVISTA-MPS-DC0F','Quezon PPO','Buenavista MPS','Encoder',true),
('SL-QUEZON-PPO-BURDEOS-MPS-4696','Quezon PPO','Burdeos MPS','Encoder',true),
('SL-QUEZON-PPO-CALAUAG-MPS-31B2','Quezon PPO','Calauag MPS','Encoder',true),
('SL-QUEZON-PPO-CANDELARIA-MPS-262F','Quezon PPO','Candelaria MPS','Encoder',true),
('SL-QUEZON-PPO-CATANAUAN-MPS-1054','Quezon PPO','Catanauan MPS','Encoder',true),
('SL-QUEZON-PPO-DOLORES-MPS-4F9B','Quezon PPO','Dolores MPS','Encoder',true),
('SL-QUEZON-PPO-GENERAL-LUNA-MPS-9FE4','Quezon PPO','General Luna MPS','Encoder',true),
('SL-QUEZON-PPO-GENERAL-NAKAR-MPS-92EA','Quezon PPO','General Nakar MPS','Encoder',true),
('SL-QUEZON-PPO-GUINAYANGAN-MPS-A839','Quezon PPO','Guinayangan MPS','Encoder',true),
('SL-QUEZON-PPO-GUMACA-MPS-57A1','Quezon PPO','Gumaca MPS','Encoder',true),
('SL-QUEZON-PPO-INFANTA-MPS-7825','Quezon PPO','Infanta MPS','Encoder',true),
('SL-QUEZON-PPO-JOMALIG-MPS-D81A','Quezon PPO','Jomalig MPS','Encoder',true),
('SL-QUEZON-PPO-LOPEZ-MPS-1D86','Quezon PPO','Lopez MPS','Encoder',true),
('SL-QUEZON-PPO-LUCBAN-MPS-0383','Quezon PPO','Lucban MPS','Encoder',true),
('SL-QUEZON-PPO-LUCENA-CCPS-7652','Quezon PPO','Lucena CCPS','Encoder',true),
('SL-QUEZON-PPO-MACALELON-MPS-C416','Quezon PPO','Macalelon MPS','Encoder',true),
('SL-QUEZON-PPO-MAUBAN-MPS-9C4C','Quezon PPO','Mauban MPS','Encoder',true),
('SL-QUEZON-PPO-MULANAY-MPS-78B5','Quezon PPO','Mulanay MPS','Encoder',true),
('SL-QUEZON-PPO-PADRE-BURGOS-MPS-13B6','Quezon PPO','Padre Burgos MPS','Encoder',true),
('SL-QUEZON-PPO-PAGBILAO-MPS-D6E6','Quezon PPO','Pagbilao MPS','Encoder',true),
('SL-QUEZON-PPO-PANUKULAN-MPS-DEE3','Quezon PPO','Panukulan MPS','Encoder',true),
('SL-QUEZON-PPO-PATNANUNGAN-MPS-AEE9','Quezon PPO','Patnanungan MPS','Encoder',true),
('SL-QUEZON-PPO-PEREZ-MPS-6EFF','Quezon PPO','Perez MPS','Encoder',true),
('SL-QUEZON-PPO-PITOGO-MPS-5783','Quezon PPO','Pitogo MPS','Encoder',true),
('SL-QUEZON-PPO-PLARIDEL-MPS-B40C','Quezon PPO','Plaridel MPS','Encoder',true),
('SL-QUEZON-PPO-POLILLO-MPS-F0AD','Quezon PPO','Polillo MPS','Encoder',true),
('SL-QUEZON-PPO-QUEZON-MPS-0986','Quezon PPO','Quezon MPS','Encoder',true),
('SL-QUEZON-PPO-REAL-MPS-759B','Quezon PPO','Real MPS','Encoder',true),
('SL-QUEZON-PPO-SAMPALOC-MPS-4273','Quezon PPO','Sampaloc MPS','Encoder',true),
('SL-QUEZON-PPO-SAN-ANDRES-MPS-976B','Quezon PPO','San Andres MPS','Encoder',true),
('SL-QUEZON-PPO-SAN-ANTONIO-MPS-CECB','Quezon PPO','San Antonio MPS','Encoder',true),
('SL-QUEZON-PPO-SAN-FRANCISCO-MPS-7EE5','Quezon PPO','San Francisco MPS','Encoder',true),
('SL-QUEZON-PPO-SAN-NARCISO-MPS-0695','Quezon PPO','San Narciso MPS','Encoder',true),
('SL-QUEZON-PPO-SARIAYA-MPS-57AE','Quezon PPO','Sariaya MPS','Encoder',true),
('SL-QUEZON-PPO-TAGKAWAYAN-MPS-A6D9','Quezon PPO','Tagkawayan MPS','Encoder',true),
('SL-QUEZON-PPO-TAYABAS-CCPS-B26E','Quezon PPO','Tayabas CCPS','Encoder',true),
('SL-QUEZON-PPO-TIAONG-MPS-E8BF','Quezon PPO','Tiaong MPS','Encoder',true),
('SL-QUEZON-PPO-UNISAN-MPS-E69A','Quezon PPO','Unisan MPS','Encoder',true),
('SL-PRO4A-226609-0C23','PRO4A','226609','System Administrator',true);
